name: Trigger stock fetch

on:
  schedule:
    # At 22:00 on every day-of-week from Monday through Friday.
    - cron: '0 22 * * 1-5'
jobs:
  build:
    name: Trigger stock refresh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        env:
          API_KEY: '${{ secrets.API_KEY }}'
        run: bash stocks.sh